// Code generated by .github/workflows/update_deps.yml from plugins.txt. DO NOT EDIT.

package main

import (
	_ "time/tzdata" // 内嵌时区数据库，精简系统上 @ 时间匹配器才可用

	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	_ "github.com/LeenHawk/caddy-edgeone-ip"
	_ "github.com/WeidiDeng/caddy-cloudflare-ip"
	_ "github.com/caddy-dns/tencentcloud"
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/caddyserver/forwardproxy"
	_ "github.com/caddyserver/jsonc-adapter"
	_ "github.com/fvbommel/caddy-combine-ip-ranges"
	_ "github.com/greenpau/caddy-security"
	_ "github.com/imgk/caddy-trojan"
	_ "github.com/lanrat/caddy-dynamic-remoteip"
	_ "github.com/mholt/caddy-events-exec"
	_ "github.com/mholt/caddy-l4"
	_ "github.com/mholt/caddy-ratelimit"
	_ "github.com/mholt/caddy-webdav"
	_ "github.com/monobilisim/caddy-ip-list"
	_ "github.com/okrc/caddy-uploadcert-tencentcloud"
	_ "github.com/porech/caddy-maxmind-geolocation"
	_ "github.com/tuzzmaniandevil/caddy-dynamic-clientip"
	_ "github.com/xcaddyplugins/caddy-trusted-cloudfront"
)

func main() {
	caddycmd.Main()
}
